boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/edit/', views.edit, name='edit'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('', views.index, name='index'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

boards/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.id}: {self.title}'
        
class Comment(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.content

boards/views.py
from django.shortcuts import render, redirect
from .models import Board, Comment
from pprint import pprint

# Create your views here.
def index(request):
    # pprint(request)
    # pprint(type(request))
    # pprint(dir(request))
    # pprint(request.scheme)
    # pprint(request.get_host())
    # pprint(request.get_full_path())
    # pprint(request.build_absolute_uri())
    # pprint(request.META)
    
    boards = Board.objects.order_by('-pk')
    context = {
        'boards': boards,
    }
    return render(request, 'boards/index.html', context)

def new(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        
        board = Board(title=title, content=content)
        board.save()
        return redirect('boards:detail', board.pk)
    else:
        return render(request, 'boards/new.html')
    
def detail(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    comments = board.comment_set.all()
    context = {
        'board': board,
        'comments': comments,
    }
    return render(request, 'boards/detail.html', context)

def delete(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail', board.pk)
    
def edit(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        # update
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.save()
        return redirect('boards:detail', board.pk)
    else:
        # edit
        context = {
            'board': board
        }
        return render(request, 'boards/edit.html', context)
        
def comments_create(request, board_pk):
    # 댓글을 달 게시물
    board = Board.objects.get(pk=board_pk)
    
    # form에서 넘어온 comment data
    content = request.POST.get('content')
    
    # 댓글 생성 및 저장
    comment = Comment(board=board, content=content)
    comment.save()
    return redirect('boards:detail', board.pk)
    
def comments_delete(request, board_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('boards:detail', board_pk)
    else:
        return redirect('boards:detail', board_pk)
    

boards/templates/boards/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

boards/templates/boards/detail.html
{% extends 'boards/base.html' %}
{% block body %}
    <h1>Detail</h1>
    <h2>{{ board.id }} 번째 글</h2>
    <hr>
    <h2>{{ board.title }}</h2>
    <p>{{ board.content }}</p>
    <p>{{ board.created_at }}</p>
    <p>{{ board.updated_at }}</p>
    <a href="{% url 'boards:index' %}">BACK</a>
    <a href="{% url 'boards:edit' board.pk %}">[수정]</a>
    <form action="{% url 'boards:delete' board.pk %}" method="POST" style="display: inline" onsubmit="return confirm('R U SURE?');">
        {% csrf_token %}
        <input type="submit" value="삭제"/>
    </form>
    
    <hr>
    {% for comment in comments %}
        <li>
            {{ comment.content }}
            <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST" style="display: inline" onsubmit="return confirm('R U SURE?');">
                {% csrf_token %}
                <input type="submit" value="삭제"/>
            </form>
        </li>
    {% empty %}
        <p><b>댓글이 없어요.</b></p>
    {% endfor %}
    <hr>
    
    <p>댓글 작성 / {{ comments | length }} 개의 댓글</p>
    <form action="{%url 'boards:comments_create' board.pk %}" method="POST">
        {% csrf_token %}
        comment : <input type="text" name="content">
        <input type="submit" name="submit"/>
    </form>
{% endblock %}

boards/templates/boards/edit.html
{% extends 'boards/base.html' %}
{% block body %}
    <h1>Edit</h1>
    <form method='POST'>
        {% csrf_token %}
        <label for="title">TITLE</label>
        <input type="text" name="title" id="title" value='{{ board.title }}'/><br>
        <label for="content">CONTENT</label>
        <input type="text" name="content" id='content' value='{{ board.content }}'/><br>
        <input type="submit" value="Submit"/>
    </form>
    <a href="{% url 'boards:index' %}">BACK</a>
{% endblock %}

boards/templates/boards/index.html
{% extends 'boards/base.html' %}
{% block body %}
    <h1>Index</h1>
    <a href="/boards/new/">글 작성</a>
    <hr>
    {% for board in boards %}
        <p>{{ board.id }}</p>
        <p>{{ board.title }}</p>
        <p>{{ board.created_at | timesince }} 전</p>
        <a href="{% url 'boards:detail' board.pk %}">글 보러가기</a>
        <hr>
    {% endfor %}
{% endblock %}

boards/templates/boards/new.html
{% extends 'boards/base.html' %}
{% block body %}
    <h1>New</h1>
    <form method='POST'>
        {% csrf_token %}
        <label for="title">TITLE</label>
        <input type="text" name="title" id="title"/><br>
        <label for="content">CONTENT</label>
        <input type="text" name="content" id='content'/><br>
        <input type="submit" value="Submit"/>
    </form>
    <a href="{% url 'boards:index' %}">BACK</a>
{% endblock %}